import Head from "next/head";
import db from "../data/database";
import { products } from "../data/products";
import { ListProductComponent } from "../components/product/list";
import { useState, useEffect } from "react";

let clearPage = () => {
  let form = document.getElementById("submitForm");
  form.reset();
};
export default function Admin() {
  const [productName, setName] = useState("");
  const [productPrice, setPrice] = useState("");
  const [productDescription, setDescription] = useState("");

  const submitNewProduct = (e) => {
    e.preventDefault();
    let priceNumber = parseFloat(productPrice);
    let admin = "Admin";
    let productImage = `https://source.unsplash.com/300x300?${productName}`;
    if (
      productName !== "" &&
      productPrice !== "" &&
      productDescription !== ""
    ) {
      let newProduct = {
        name: productName,
        price: priceNumber,
        description: productDescription,
        image: productImage.toString(),
        flag: admin,
      };
      products.push(newProduct);
      console.log(products);
    }
    clearPage();
  };

  return (
    <div>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <form
          id="submitForm"
          className="container mx-auto"
          onSubmit={submitNewProduct}
        >
          <div className="flex flex-wrap -mx-3 mb-6">
            <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
              <label
                htmlFor="name"
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
              >
                Name
              </label>
              <input
                type="text"
                className="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                name="name"
                onChange={(e) => setName(e.target.value)}
              />
            </div>
            <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
              <label
                htmlFor="price"
                className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
              >
                Price
              </label>
              <input
                type="text"
                className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                name="price"
                onChange={(e) => setPrice(e.target.value)}
              />
            </div>
            <div className="flex flex-wrap -mx-3 mb-6">
              <div className="w-full px-3">
                <label
                  htmlFor="description"
                  className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                >
                  Description
                </label>
                <input
                  type="text"
                  className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  rowSpan="10"
                  name="description"
                  onChange={(e) => setDescription(e.target.value)}
                />
              </div>
            </div>
            <div>
              <button
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded a"
                type="submit"
                value="Enter new Product"
              >
                Submit
              </button>
            </div>
          </div>
        </form>
      </div>
      <div className="container mx-auto">
        <h1 className="font-bold text-xl p-3">Next Shop Products</h1>
        <ListProductComponent products={products} />
      </div>
    </div>
  );
}
