import Head from "next/head";
import { ListProductComponent } from "../components/product/list";
import { products } from "../data/products";
import { useState } from "react";
import { CartProductComponent } from "../components/product/cart";

export default function Home() {
  const [cartItems, setCartItems] = useState([]);
  const handleAddToCartClick = (product) => {
    const existingItemFromCart = cartItems.find(
      (item) => item.name === product.name
    );
    let newCartItems = [];

    if (existingItemFromCart) {
      newCartItems = cartItems.map((item) => {
        if (item.name === product.name) item.count += 1;

        return item;
      });
    } else {
      newCartItems = [...cartItems, { ...product, count: 1 }];
    }

    setCartItems(newCartItems);
  };

  const handleRemoveFromCart = (product) => {
    const existingItemFromCart = cartItems.find(
      (item) => item.name === product.name
    );
    let newCartItems = [];

    if (existingItemFromCart.count === 1) {
      newCartItems = cartItems.filter((item) => item.name !== product.name);
    } else {
      newCartItems = cartItems.map((item) => {
        if (item.name === product.name) item.count -= 1;

        return item;
      });
    }

    setCartItems(newCartItems);
  };

  const handleClearCart = () => {
    setCartItems([]);
  };

  return (
    <div>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <h1 className="font-bold text-xl p-3">Next Shop</h1>
        <ListProductComponent
          products={products}
          handleAddToCartClick={handleAddToCartClick}
        />

        {cartItems.length > 0 && (
          <div>
            <CartProductComponent
              products={cartItems}
              handleClearCart={handleClearCart}
              handleRemoveFromCart={handleRemoveFromCart}
            />
          </div>
        )}
      </div>
    </div>
  );
}
