import Head from "next/head";
import { ListProductComponent } from "../components/product/list";
import { products } from "../data/products";
import { CartProductComponent } from "../components/product/cart";
import { useCart } from "../hooks/cart";
import Link from "next/link";
import { useFavoriteCart } from "../hooks/favorites";

export default function Home() {
  const {
    cartItems,
    handleClearCart,
    handleAddToCartClick,
    handleRemoveFromCart,
  } = useCart();

  const {
    handleAddFavoriteCart
  } = useFavoriteCart();

  return (
    <div>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <h1 className="font-bold text-xl p-3">Next Shop</h1>
        <ListProductComponent
          products={products}
          handleAddToCartClick={handleAddToCartClick}
          handleAddFavoriteCart={handleAddFavoriteCart}
        />

        {cartItems.length > 0 && (
          <div>
            <CartProductComponent
              products={cartItems}
              handleClearCart={handleClearCart}
              handleRemoveFromCart={handleRemoveFromCart}
            />
          </div>
        )}
      </div>
      <Link  href="/order">
          <a className="px-3 py-2 bg-indigo-200 text-gray-800">Your order</a>
      </Link>
      <Link  href="/favorites">
          <a className="px-3 py-2 mx-3 bg-indigo-200 text-gray-800">go to Favorites</a>
      </Link>
    </div>
  );
}
